component: flask
name: helloworld
org: orgDemo
app: appDemo
stage: dev

inputs:
  src:
    hook: 'pip install -r requirements.txt -t ./'
    dist: ./
    exclude:
      - .env
  region: ap-hongkong
  runtime: Python3.6
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
